### ISSUE TITLE
Add documentation for the CareCommunication message

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom-carecommunication#4]
•	Vi synes, at der mangler beskrivelse under reply og forward i den tekniske dokumentation. Den tekst der står der er, i vores øjne, ikke fyldestgørende og derfor heller ikke helt i overensstemmelse med den forretningsmæssige dokumentation: http://build.fhir.org/ig/hl7dk/dk-medcom/StructureDefinition-medcom-careCommunication-message.html

**Comment by tmsMedcom** [comment]
@MedComAnders har du et bud på, hvad der bliver efterspurgt eller om det er håndteret? Obs: har opdateret en del i dag i CareCommunication

**Comment by MedComAnders** [comment]
> @MedComAnders har du et bud på, hvad der bliver efterspurgt eller om det er håndteret? Obs: har opdateret en del i dag i CareCommunication

Det ser umildbart ud til at der er udarbejdet beskrivelser for de nævnte scenarier. Så hvis du mener de er fyldestgørende, kan vi godt lukke dette issue. - er min tanke
