### ISSUE TITLE
CareCommunication contentString skal have type xhtml stedet for string

### ISSUE THREAD

**Issue by medcomire** [hl7dk/dk-medcom-carecommunication#7]
Short tekst skal indeholde en beskrivelse af at xhtml er kompliment med narrative tekst formatet

**Comment by tmsMedcom** [comment]
add: 
* element ^short = " xhtml or plain content of the message "
* element ^definition = "xhtml shall be used to markup a text. The xhtml shall be compliant with the narrative text format. Otherwise, it is allowed to use plain text. "

**Comment by tmsMedcom** [comment]
is handled
